name: Secrets and Environment variables

on: 
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{secrets.API_KEY}}
    steps:
      - name: Display API Key
        run: echo "The API key is $VITE_API_KEY"
